# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.


File automatically generated. See the documentation to update questions/answers/hints programmatically.


Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.


In [2]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)


In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)


In [8]:
hint(2)
print(np.__version__)
np.show_config()

hint: np.__version__, np.show_config)
1.25.2
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language

#### 3. Create a null vector of size 10 (★☆☆)


In [10]:
null_vec = np.zeros(10)
null_vec

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)


In [13]:
hint(4)
print(null_vec.size)
print(null_vec.itemsize)

hint: size, itemsize
10
8


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)


In [22]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)


In [23]:
null_vec[4] = 1
null_vec

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)


In [26]:
arange_vec = np.arange(10, 50)
arange_vec

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)


In [29]:
hint(8)
reverse_arange_vec = arange_vec[::-1]
reverse_arange_vec

hint: array[::-1]


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)


In [35]:
hint(9)
arange_matrix = np.arange(9).reshape(3, 3)
arange_matrix

hint: reshape


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)


In [56]:
list = [1, 2, 0, 0, 4, 0]
non_zero_idx = tuple(np.array([i for i, v in enumerate(list) if v]))
print(non_zero_idx)

hint(10)
non_zero_idx = np.nonzero(list)
non_zero_idx

(0, 1, 4)
hint: np.nonzero


(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)


In [51]:
hint(11)
identity_matrix = np.eye(3)
identity_matrix

hint: np.eye


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)


In [54]:
random_matrix = np.random.random((3, 3, 3))
random_matrix

array([[[0.95508834, 0.05020932, 0.38373463],
        [0.23962888, 0.13358002, 0.74650712],
        [0.72756854, 0.24759988, 0.79386588]],

       [[0.31400339, 0.41569823, 0.35741695],
        [0.18129375, 0.40179329, 0.10528801],
        [0.33661974, 0.68730179, 0.93267939]],

       [[0.20975321, 0.23641349, 0.77422578],
        [0.49452119, 0.16010192, 0.1787374 ],
        [0.24274503, 0.46763821, 0.35254232]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)


In [58]:
random_matrix = np.random.random((10, 10))
min_val, max_val = random_matrix.min(), random_matrix.max()
print(f"min={min_val}, max={max_val}")

min=0.0010562561555893524, max=0.9992476022773893


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)


In [89]:
random_vec = np.random.random(30)
mean_val = np.mean(random_vec)
mean_val

0.4714383561793961

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)


In [60]:
hint(15)
ones_matrix = np.ones((10, 10))
ones_matrix[1:-1, 1:-1] = 0
ones_matrix

hint: array[1:-1, 1:-1]


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)


In [63]:
hint(16)
help(np.pad)
matrix_with_border = np.pad(ones_matrix, ((1, 1), (1, 1)))
matrix_with_border

hint: np.pad
Help on _ArrayFunctionDispatcher in module numpy:

pad(array, pad_width, mode='constant', **kwargs)
    Pad an array.
    
    Parameters
    ----------
    array : array_like of rank N
        The array to pad.
    pad_width : {sequence, array_like, int}
        Number of values padded to the edges of each axis.
        ``((before_1, after_1), ... (before_N, after_N))`` unique pad widths
        for each axis.
        ``(before, after)`` or ``((before, after),)`` yields same before
        and after pad for each axis.
        ``(pad,)`` or ``int`` is a shortcut for before = after = pad width
        for all axes.
    mode : str or function, optional
        One of the following string values or a user supplied function.
    
        'constant' (default)
            Pads with a constant value.
        'edge'
            Pads with the edge values of array.
        'linear_ramp'
            Pads with the linear ramp between end_value and the
            array edge value.
   

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```


In [67]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)


In [73]:
hint(18)
help(np.diag)
diagonal_matrix = np.diag(np.arange(1, 5), k=-1)
diagonal_matrix

hint: np.diag
Help on _ArrayFunctionDispatcher in module numpy:

diag(v, k=0)
    Extract a diagonal or construct a diagonal array.
    
    See the more detailed documentation for ``numpy.diagonal`` if you use this
    function to extract a diagonal and wish to write to the resulting array;
    whether it returns a copy or a view depends on what version of numpy you
    are using.
    
    Parameters
    ----------
    v : array_like
        If `v` is a 2-D array, return a copy of its `k`-th diagonal.
        If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
        diagonal.
    k : int, optional
        Diagonal in question. The default is 0. Use `k>0` for diagonals
        above the main diagonal, and `k<0` for diagonals below the main
        diagonal.
    
    Returns
    -------
    out : ndarray
        The extracted diagonal or constructed diagonal array.
    
    See Also
    --------
    diagonal : Return specified diagonals.
    diagflat : Create a 2-D array 

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)


In [75]:
hint(19)
checkerboard_matrix = np.zeros((8, 8))
checkerboard_matrix[1::2, ::2] = 1
checkerboard_matrix

hint: array[::2]


array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)


In [83]:
hint(20)
help(np.unravel_index)
np.unravel_index(99, (6, 7, 8))

hint: np.unravel_index
Help on _ArrayFunctionDispatcher in module numpy:

unravel_index(...)
    unravel_index(indices, shape, order='C')
    
    Converts a flat index or array of flat indices into a tuple
    of coordinate arrays.
    
    Parameters
    ----------
    indices : array_like
        An integer array whose elements are indices into the flattened
        version of an array of dimensions ``shape``. Before version 1.6.0,
        this function accepted just one index value.
    shape : tuple of ints
        The shape of the array to use for unraveling ``indices``.
    
        .. versionchanged:: 1.16.0
            Renamed from ``dims`` to ``shape``.
    
    order : {'C', 'F'}, optional
        Determines whether the indices should be viewed as indexing in
        row-major (C-style) or column-major (Fortran-style) order.
    
        .. versionadded:: 1.6.0
    
    Returns
    -------
    unraveled_coords : tuple of ndarray
        Each array in the tuple has the same s

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)


In [86]:
hint(21)
help(np.tile)
checkerboard_matrix = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
checkerboard_matrix

hint: np.tile
Help on _ArrayFunctionDispatcher in module numpy:

tile(A, reps)
    Construct an array by repeating A the number of times given by reps.
    
    If `reps` has length ``d``, the result will have dimension of
    ``max(d, A.ndim)``.
    
    If ``A.ndim < d``, `A` is promoted to be d-dimensional by prepending new
    axes. So a shape (3,) array is promoted to (1, 3) for 2-D replication,
    or shape (1, 1, 3) for 3-D replication. If this is not the desired
    behavior, promote `A` to d-dimensions manually before calling this
    function.
    
    If ``A.ndim > d``, `reps` is promoted to `A`.ndim by pre-pending 1's to it.
    Thus for an `A` of shape (2, 3, 4, 5), a `reps` of (2, 2) is treated as
    (1, 1, 2, 2).
    
    Note : Although tile may be used for broadcasting, it is strongly
    recommended to use numpy's broadcasting operations and functions.
    
    Parameters
    ----------
    A : array_like
        The input array.
    reps : array_like
        The num

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)


In [126]:
answer(22)
matrix = np.random.random((5, 5))
standardized_matrix = matrix - np.mean(matrix) / np.std(matrix)
standardized_matrix

Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)


array([[-0.71283954, -0.85294688, -1.35847957, -0.46301539, -1.08233558],
       [-1.34652311, -0.99523728, -1.25825418, -0.68510507, -1.11423152],
       [-1.00781388, -1.16377424, -0.56065512, -0.60207573, -1.19751767],
       [-0.44696619, -1.31817595, -1.14381915, -1.10171137, -1.23241648],
       [-0.4067695 , -0.41014752, -0.54745473, -1.28657579, -1.21149652]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)


In [93]:
hint(23)
color = np.dtype([("r", np.ubyte, 1), ("g", np.ubyte, 1), ("b", np.ubyte, 1), ("a", np.ubyte, 1)])

hint: np.dtype


/var/folders/7t/dtfknjpn0xv4mm1vpxdr54sm0000gn/T/ipykernel_4878/2158838085.py:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)


In [100]:
hint(24)
matrix1 = np.arange(15).reshape((5, 3))
matrix2 = np.arange(6).reshape((3, 2))
matrix = matrix1 @ matrix2
# matrix = np.matmul(matrix1, matrix2)
matrix

hint:


array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)


In [105]:
hint(25)
vector = np.arange(11)
vector[(vector > 3) & (vector <= 8)] *= -1
vector

hint: >, <


array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```


In [108]:
help(sum)
help(np.sum)
print(sum(range(5), -1))
print(np.sum(range(5), -1))

Help on _ArrayFunctionDispatcher in module numpy:

sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
    Sum of array elements over a given axis.
    
    Parameters
    ----------
    a : array_like
        Elements to sum.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a sum is performed.  The default,
        axis=None, will sum all of the elements of the input array.  If
        axis is negative it counts from the last to the first axis.
    
        .. versionadded:: 1.7.0
    
        If axis is a tuple of ints, a sum is performed on all of the axes
        specified in the tuple instead of a single axis or all the axes as
        before.
    dtype : dtype, optional
        The type of the returned array and of the accumulator in which the
        elements are summed.  The dtype of `a` is used by default unless `a`
        has an integer dtype of less precision than the default platform
        i

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```


In [114]:
Z = np.arange(6)
print(Z**Z)
print(2 << Z >> 2)
print(Z < -Z)
print(1j * Z)
print(Z / 1 / 1)
print(Z < Z > Z)

[   1    1    4   27  256 3125]
[ 0  1  2  4  8 16]
[False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j]
[0. 1. 2. 3. 4. 5.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions? (★☆☆)

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```


In [117]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[0.]


/var/folders/7t/dtfknjpn0xv4mm1vpxdr54sm0000gn/T/ipykernel_4878/3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/var/folders/7t/dtfknjpn0xv4mm1vpxdr54sm0000gn/T/ipykernel_4878/3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/var/folders/7t/dtfknjpn0xv4mm1vpxdr54sm0000gn/T/ipykernel_4878/3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)


In [121]:
round_vec = np.random.uniform(-10, 10, 10)
round_vec = np.copysign(np.ceil(abs(round_vec)), round_vec)
round_vec

array([-5.,  8., -5.,  4., -9., -3.,  1., -9., -9., -7.])

#### 30. How to find common values between two arrays? (★☆☆)


In [124]:
hint(30)
help(np.intersect1d)
vector1 = np.random.randint(0, 10, 10)
vector2 = np.random.randint(0, 10, 10)
common_vector = np.intersect1d(vector1, vector2)
common_vector

hint: np.intersect1d
Help on _ArrayFunctionDispatcher in module numpy:

intersect1d(ar1, ar2, assume_unique=False, return_indices=False)
    Find the intersection of two arrays.
    
    Return the sorted, unique values that are in both of the input arrays.
    
    Parameters
    ----------
    ar1, ar2 : array_like
        Input arrays. Will be flattened if not already 1D.
    assume_unique : bool
        If True, the input arrays are both assumed to be unique, which
        can speed up the calculation.  If True but ``ar1`` or ``ar2`` are not
        unique, incorrect results and out-of-bounds indices could result.
        Default is False.
    return_indices : bool
        If True, the indices which correspond to the intersection of the two
        arrays are returned. The first instance of a value is used if there are
        multiple. Default is False.
    
        .. versionadded:: 1.15.0
    
    Returns
    -------
    intersect1d : ndarray
        Sorted 1D array of common an

array([0, 3, 4, 5, 7, 8])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)


In [129]:
# hint(31)
# answer(31)

# defaults = np.seterr(all="ignore")
# Z = np.ons(1) / 0

# _ = np.seterr(**defaults)

# with np.errstate(all="ignore"):
#     np.arrange(3) / 0Z = np.ons(1) / 0

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```


In [130]:
np.sqrt(-1) == np.emath.sqrt(-1)

/var/folders/7t/dtfknjpn0xv4mm1vpxdr54sm0000gn/T/ipykernel_4878/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)


In [5]:
hint(33)
today = np.datetime64("today")
timedelta = np.timedelta64(1, "D")
print(today)
yesterday = today - timedelta
print(yesterday)
tomorrow = today + timedelta
print(tomorrow)

hint: np.datetime64, np.timedelta64
2023-09-17
2023-09-16
2023-09-18


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)


In [16]:
hint(34)
date_vec = np.arange("2016-07", "2016-08", dtype="datetime64[D]")
date_vec

hint: np.arange(dtype=datetime64['D'])


array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)


In [19]:
A = np.ones(5)
B = np.ones(5) * 2
np.add(A, B, out=B)
np.negative(A, out=A)
np.divide(A, 2, out=A)
np.multiply(A, B, out=A)
A

array([-1.5, -1.5, -1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)


In [22]:
hint(36)
vec = np.random.uniform(0, 10, 10)
print(vec // 1)
print(vec - vec % 1)
print(np.floor(vec))
print(np.ceil(vec) - 1)
print(vec.astype(int).astype(float))
print(np.trunc(vec))

hint: %, np.floor, astype, np.trunc
[8. 3. 6. 2. 4. 2. 9. 7. 4. 5.]
[8. 3. 6. 2. 4. 2. 9. 7. 4. 5.]
[8. 3. 6. 2. 4. 2. 9. 7. 4. 5.]
[8. 3. 6. 2. 4. 2. 9. 7. 4. 5.]
[8. 3. 6. 2. 4. 2. 9. 7. 4. 5.]
[8. 3. 6. 2. 4. 2. 9. 7. 4. 5.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)


In [30]:
vec = np.zeros((5, 5))
vec += np.arange(5)
vec

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)


In [35]:
hint(38)
from typing import Iterator


def generate_int() -> Iterator[int]:
    for i in range(10):
        yield i


vec = np.fromiter(generate_int(), dtype=float, count=-1)
vec

hint: np.fromiter


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)


In [39]:
hint(39)
help(np.linspace)
vec = np.linspace(0, 1, 11, endpoint=False)[1:]
vec

hint: np.linspace
Help on _ArrayFunctionDispatcher in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)


In [50]:
hint(40)
vec = np.random.random(10)
vec.sort()
vec

hint: sort


array([0.17919944, 0.29999256, 0.3984429 , 0.49366548, 0.56659652,
       0.65087742, 0.74674362, 0.75716412, 0.84223577, 0.91127703])

#### 41. How to sum a small array faster than np.sum? (★★☆)


In [53]:
hint(41)
np.add.reduce(vec)

hint: np.add.reduce


5.846194839686358

#### 42. Consider two random array A and B, check if they are equal (★★☆)


In [59]:
hint(42)
help(np.allclose)
A = np.random.random(5)
B = np.random.random(5)
print(np.allclose(A, B))
print(np.array_equal(A, B))

hint: np.allclose, np.array_equal
Help on _ArrayFunctionDispatcher in module numpy:

allclose(a, b, rtol=1e-05, atol=1e-08, equal_nan=False)
    Returns True if two arrays are element-wise equal within a tolerance.
    
    The tolerance values are positive, typically very small numbers.  The
    relative difference (`rtol` * abs(`b`)) and the absolute difference
    `atol` are added together to compare against the absolute difference
    between `a` and `b`.
    
    NaNs are treated as equal if they are in the same place and if
    ``equal_nan=True``.  Infs are treated as equal if they are in the same
    place and of the same sign in both arrays.
    
    Parameters
    ----------
    a, b : array_like
        Input arrays to compare.
    rtol : float
        The relative tolerance parameter (see Notes).
    atol : float
        The absolute tolerance parameter (see Notes).
    equal_nan : bool
        Whether to compare NaN's as equal.  If True, NaN's in `a` will be
        conside

#### 43. Make an array immutable (read-only) (★★☆)


In [61]:
hint(43)
vec.flags.writeable = False

hint: flags.writeable


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)


In [63]:
hint(44)
matrix = np.random.random((10, 2))
x, y = matrix[:, 0], matrix[:, 1]
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)
print((r, theta))

hint: np.sqrt, np.arctan2
(array([0.67244098, 0.90707869, 0.90855496, 0.40817899, 0.72823586,
       1.1721593 , 1.19824927, 0.75188688, 0.95653264, 0.64790953]), array([1.41841118, 1.06623814, 0.02746366, 0.39844532, 0.65316461,
       0.99845165, 0.93233233, 1.40512108, 0.70834583, 0.71976414]))


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)


In [68]:
hint(45)
help(np.argmax)
vec = np.random.random(10)
# vec[vec == vec.max()] = 0
vec[vec.argmax()] = 0
vec

hint: argmax
Help on _ArrayFunctionDispatcher in module numpy:

argmax(a, axis=None, out=None, *, keepdims=<no value>)
    Returns the indices of the maximum values along an axis.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axis : int, optional
        By default, the index is into the flattened array, otherwise
        along the specified axis.
    out : array, optional
        If provided, the result will be inserted into this array. It should
        be of the appropriate shape and dtype.
    keepdims : bool, optional
        If this is set to True, the axes which are reduced are left
        in the result as dimensions with size one. With this option,
        the result will broadcast correctly against the array.
    
        .. versionadded:: 1.22.0
    
    Returns
    -------
    index_array : ndarray of ints
        Array of indices into the array. It has the same shape as `a.shape`
        with the dimension along `axis` removed. If `keepdims

array([0.34864955, 0.27474856, 0.34851557, 0.30024147, 0.26122133,
       0.19871367, 0.02192384, 0.        , 0.29898179, 0.36414788])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)


In [70]:
hint(46)
point = np.zeros((5, 5), [("x", float), ("y", float)])
point["x"], point["y"] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
point

hint: np.meshgrid


array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)


In [72]:
hint(47)
X = np.arange(1, 6)
Y = np.arange(1, 6)
C = 1 / np.subtract.outer(X, Y)
C

hint: np.subtract.outer


/var/folders/7t/dtfknjpn0xv4mm1vpxdr54sm0000gn/T/ipykernel_996/2756566339.py:4: RuntimeWarning: divide by zero encountered in divide
  C = 1 / np.subtract.outer(X, Y)


array([[        inf, -1.        , -0.5       , -0.33333333, -0.25      ],
       [ 1.        ,         inf, -1.        , -0.5       , -0.33333333],
       [ 0.5       ,  1.        ,         inf, -1.        , -0.5       ],
       [ 0.33333333,  0.5       ,  1.        ,         inf, -1.        ],
       [ 0.25      ,  0.33333333,  0.5       ,  1.        ,         inf]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)


In [75]:
hint(48)
for dtype in (np.int8, np.int32, np.int64):
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

for dtype in (np.float32, np.float64):
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

hint: np.iinfo, np.finfo, eps
-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)


In [78]:
hint(49)
np.set_printoptions(threshold=float("inf"))
vec = np.zeros((40, 40))
vec

hint: np.set_printoptions


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
   

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)


In [81]:
hint(50)
found_scalar = 0.5
vec = np.random.random(10)
print(vec[np.abs(vec - found_scalar).argmin()])

hint: argmin
0.5304500675430257


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)


In [87]:
hint(51)
position_with_color = np.zeros(
    10, [("position", [("x", float), ("y", float)]), ("color", [("r", float), ("g", float), ("b", float)])]
)
position_with_color["position"]

hint: dtype


array([(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.),
       (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
      dtype=[('x', '<f8'), ('y', '<f8')])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)


In [90]:
hint(52)
answer(52)
points = np.random.random((100, 2))
X, Y = np.atleast_2d(points[:, 0], points[:, 1])
D = np.sqrt((X - X.T) ** 2 + (Y - Y.T) ** 2)
D

hint: np.atleast_2d, T, np.sqrt
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)


array([[0.        , 0.71755373, 0.19677849, 0.6634308 , 0.43813633,
        0.35705625, 0.50350971, 0.30084685, 0.78063855, 0.73875025,
        0.41881925, 0.92208025, 0.83719598, 0.80541277, 0.6137136 ,
        0.78005388, 0.64846416, 0.26956831, 1.0365365 , 0.7378955 ,
        0.52695252, 0.98585528, 0.14778526, 0.81585359, 0.73533216,
        0.07759152, 0.19459036, 0.47588851, 0.95120245, 0.15180199,
        0.37105873, 0.55242123, 0.8754356 , 0.71786108, 0.25226483,
        0.7178398 , 0.86655455, 0.60064807, 0.67219926, 0.76702207,
        0.80186918, 0.74197144, 0.43753603, 0.60986356, 1.06842422,
        0.37635891, 0.40694525, 0.75510361, 0.47333481, 0.62228304,
        0.73588779, 0.33758793, 0.2860658 , 0.37337298, 0.49531907,
        0.05919148, 0.63759531, 0.43134688, 0.10670686, 0.44935091,
        1.09197525, 1.11181585, 0.7804401 , 0.72572488, 0.75459568,
        0.83720553, 0.2254688 , 0.1078252 , 0.82383641, 0.37875018,
        0.64201643, 0.47033016, 0.72226105, 0.71

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?


In [95]:
hint(53)
vec = np.random.random(10).astype(np.float32)
vec.view(np.int32)

hint: view and [:] =


array([1060122007, 1065105641, 1018140459, 1063656823, 1064115098,
       1059843920, 1060416496, 1053846495, 1059226784, 1060463134],
      dtype=int32)

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```


In [97]:
hint(54)
from io import StringIO


s = StringIO(
    """1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
"""
)
Z = np.genfromtxt(s, delimiter=",", dtype=np.int32)
print(Z)

hint: np.genfromtxt
[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)


In [99]:
hint(55)
matrix = np.arange(9).reshape((3, 3))
for i, v in np.ndenumerate(matrix):
    print(i, v)
for i in np.ndindex(matrix.shape):
    print(i)

hint: np.ndenumerate, np.ndindex
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0)
(0, 1)
(0, 2)
(1, 0)
(1, 1)
(1, 2)
(2, 0)
(2, 1)
(2, 2)


#### 56. Generate a generic 2D Gaussian-like array (★★☆)


In [100]:
hint(56)

hint: np.meshgrid, np.exp


#### 57. How to randomly place p elements in a 2D array? (★★☆)


In [107]:
hint(57)
help(np.random.choice)
n, p = 10, 3
matrix = np.random.random((n, n))
np.put(matrix, np.random.choice(range(n * n), p, replace=False), 1)
matrix

hint: np.put, np.random.choice
Help on built-in function choice:

choice(...) method of numpy.random.mtrand.RandomState instance
    choice(a, size=None, replace=True, p=None)
    
    Generates a random sample from a given 1-D array
    
    .. versionadded:: 1.7.0
    
    .. note::
        New code should use the `~numpy.random.Generator.choice`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    a : 1-D array-like or int
        If an ndarray, a random sample is generated from its elements.
        If an int, the random sample is generated as if it were ``np.arange(a)``
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, in which case a
        single value is returned.
    replace : boolean, optional
        Whether the sample is with or without replacement. Defa

array([[1.        , 0.91448201, 0.57080942, 0.12248268, 0.92405629,
        0.24513578, 1.        , 0.23273917, 0.9912417 , 0.35341367],
       [0.34145683, 0.9882331 , 0.35137773, 0.00492756, 0.20104459,
        0.71094221, 0.5300415 , 0.84076495, 0.19054744, 0.72615644],
       [0.20587469, 0.66740077, 0.88263773, 0.29703618, 0.30498653,
        0.83912971, 0.44963221, 0.35293082, 0.99180406, 0.62261652],
       [0.45727667, 0.25325043, 0.52779729, 0.05956508, 0.88072351,
        0.07625333, 0.07015697, 0.07603538, 0.65590416, 0.25097401],
       [0.65864227, 0.07425263, 0.73355909, 0.90222036, 0.97146733,
        0.35621066, 0.79238544, 0.90058899, 0.91873104, 0.11594489],
       [0.05244919, 0.2235791 , 0.71978396, 0.17478218, 0.97841487,
        0.41515712, 0.27224286, 0.74168031, 0.08853693, 0.46509286],
       [0.29670916, 0.92687138, 0.28765027, 0.93298724, 0.55338014,
        0.58341839, 0.73655173, 1.        , 0.03518614, 0.49493214],
       [0.93087626, 0.24020378, 0.9698555

#### 58. Subtract the mean of each row of a matrix (★★☆)


In [110]:
hint(58)
matrix = np.arange(9).reshape((3, 3))
matrix - matrix.mean(axis=1, keepdims=True)

hint: mean(axis=,keepdims=)


array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

#### 59. How to sort an array by the nth column? (★★☆)


In [116]:
hint(59)
help(np.argsort)
matrix = np.random.randint(0, 10, (3, 3))
print(matrix)
print(matrix[:, 1].argsort())
matrix[matrix[:, 1].argsort()]

hint: argsort
Help on _ArrayFunctionDispatcher in module numpy:

argsort(a, axis=-1, kind=None, order=None)
    Returns the indices that would sort an array.
    
    Perform an indirect sort along the given axis using the algorithm specified
    by the `kind` keyword. It returns an array of indices of the same shape as
    `a` that index data along the given axis in sorted order.
    
    Parameters
    ----------
    a : array_like
        Array to sort.
    axis : int or None, optional
        Axis along which to sort.  The default is -1 (the last axis). If None,
        the flattened array is used.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
        and 'mergesort' use timsort under the covers and, in general, the
        actual implementation will vary with data type. The 'mergesort' option
        is retained for backwards compatibility.
    
        .. versionchanged:: 1.15.0

array([[7, 0, 9],
       [5, 0, 1],
       [0, 3, 1]])

#### 60. How to tell if a given 2D array has null columns? (★★☆)


In [118]:
hint(60)
np.isnan(matrix).all(axis=0)

hint: any, ~


array([False, False, False])

#### 61. Find the nearest value from a given value in an array (★★☆)


In [122]:
matrix[np.abs(matrix - 0.5).argmin()]

array([0, 3, 1])

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)


In [124]:
hint(62)
help(np.nditer)

hint: np.nditer
Help on class nditer in module numpy:

class nditer(builtins.object)
 |  nditer(op, flags=None, op_flags=None, op_dtypes=None, order='K', casting='safe', op_axes=None, itershape=None, buffersize=0)
 |  
 |  Efficient multi-dimensional iterator object to iterate over arrays.
 |  To get started using this object, see the
 |  :ref:`introductory guide to array iteration <arrays.nditer>`.
 |  
 |  Parameters
 |  ----------
 |  op : ndarray or sequence of array_like
 |      The array(s) to iterate over.
 |  
 |  flags : sequence of str, optional
 |        Flags to control the behavior of the iterator.
 |  
 |        * ``buffered`` enables buffering when required.
 |        * ``c_index`` causes a C-order index to be tracked.
 |        * ``f_index`` causes a Fortran-order index to be tracked.
 |        * ``multi_index`` causes a multi-index, or a tuple of indices
 |          with one per iteration dimension, to be tracked.
 |        * ``common_dtype`` causes all the operands to

#### 63. Create an array class that has a name attribute (★★☆)


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)


In [128]:
hint(64)
answer(64)
vec = np.ones(10)
vec2 = np.random.randint(0, len(vec), 20)
vec += np.bincount(vec2, minlength=len(vec))
vec

hint: np.bincount | np.add.at
# Author: Brett Olsen

Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1)
print(Z)


array([3., 3., 2., 2., 4., 1., 4., 3., 4., 4.])

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)


In [131]:
hint(65)
X = [1, 2, 3, 4, 5, 6]
I = [1, 3, 9, 3, 4, 1]
F = np.bincount(I, X)
F

hint: np.bincount


array([0., 7., 0., 6., 5., 0., 0., 0., 0., 3.])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)


In [4]:
hint(66)
answer(66)

hint: np.unique
# Author: Fisher Wang

w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

# Faster version
# Author: Mark Setchell
# https://stackoverflow.com/a/59671950/2836621

w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)

# View each pixel as a single 24-bit integer, rather than three 8-bit bytes
I24 = np.dot(I.astype(np.uint32),[1,256,65536])

# Count unique colours
n = len(np.unique(I24))
print(n)


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)


In [7]:
hint(67)
answer(67)
tensor = np.random.randint(0, 5, (2, 2, 2, 2))
print(tensor)
total = tensor.sum(axis=(-2, -1))
total

hint: sum(axis=(-2,-1))
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)
[[[[0 0]
   [1 0]]

  [[2 4]
   [1 0]]]


 [[[1 4]
   [2 2]]

  [[4 4]
   [3 1]]]]


array([[ 1,  7],
       [ 9, 12]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices? (★★★)


In [9]:
hint(68)
answer(68)

hint: np.bincount
# Author: Jaime Fernández del Río

D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())


#### 69. How to get the diagonal of a dot product? (★★★)


In [11]:
matrix1 = np.random.randint(0, 5, (3, 3))
matrix2 = np.random.randint(0, 5, (3, 3))
np.einsum("ij,ji->i", matrix1, matrix2)

array([12,  8,  8])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)


In [14]:
hint(70)
vec = np.arange(1, 6)
inserted_vec = np.zeros(3 * (len(vec) - 1) + len(vec))
inserted_vec[::4] = vec
inserted_vec

hint: array[::4]


array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)


In [20]:
hint(71)
matrix1 = np.random.randint(0, 5, (5, 5, 3))
matrix2 = np.random.randint(0, 5, (5, 5))
matrix1 * matrix2[:, :, None]

hint: array[:, :, None]


array([[[ 4,  0,  4],
        [ 0,  0,  0],
        [ 4,  0, 12],
        [ 0,  9,  9],
        [16, 12,  4]],

       [[ 8, 16, 12],
        [12,  0,  6],
        [12,  0,  3],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 6,  3,  9],
        [ 0,  0,  0],
        [ 8,  8,  4],
        [ 0,  0,  2],
        [ 6,  8,  0]],

       [[ 4,  1,  2],
        [ 6,  6,  8],
        [ 3,  2,  0],
        [ 4,  2,  1],
        [ 0,  0,  0]],

       [[ 0,  3, 12],
        [ 8,  4, 16],
        [12,  0, 16],
        [ 0, 12,  8],
        [ 3,  0,  0]]])

#### 72. How to swap two rows of an array? (★★★)


In [53]:
matrix = np.arange(9).reshape((3, 3))
print(matrix)
# matrix[:,(1,0)] = matrix[:,(0,1)]
# matrix[:2] = matrix[1::-1]
matrix[:, :2] = matrix[:, 1::-1]
matrix

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles (★★★)


In [55]:
hint(73)

hint: repeat, np.roll, np.sort, view, np.unique


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)


In [60]:
hint(74)
C = np.bincount([1, 1, 2, 3, 4, 4, 6])  # [0, 2, 1, 1, 2, 0, 1]
A = np.repeat(np.arange(len(C)), C)
print(np.bincount(A))

hint: np.repeat
[0 2 1 1 2 0 1]


#### 75. How to compute averages using a sliding window over an array? (★★★)


In [61]:
hint(75)

hint: np.cumsum, from numpy.lib.stride_tricks import sliding_window_view (np>=1.20.0)


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)


In [62]:
hint(76)

hint: from numpy.lib import stride_tricks, from numpy.lib.stride_tricks import sliding_window_view (np>=1.20.0)


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)


In [66]:
hint(77)
vec = np.random.randint(0, 2, 10)
print(vec)
np.logical_not(vec, out=vec)

hint: np.logical_not, np.negative
[0 1 0 0 0 0 1 0 1 0]


array([1, 0, 1, 1, 1, 1, 0, 1, 0, 1])

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)


In [67]:
hint(78)

No hints provided...


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)


In [68]:
hint(79)

No hints provided...


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)


In [69]:
hint(80)

hint: minimum maximum


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)


In [ ]:
# same as 76

#### 82. Compute a matrix rank (★★★)


In [3]:
matrix = np.random.randint(0, 5, (5, 5))
np.linalg.matrix_rank(matrix)

5

#### 83. How to find the most frequent value in an array?


In [75]:
matrix = np.random.randint(0, 5, 10)
np.bincount(matrix).argmax()

4

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)


In [77]:
hint(84)

hint: stride_tricks.as_strided, from numpy.lib.stride_tricks import sliding_window_view (np>=1.20.0)


#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)


In [78]:
# warning that user defined class inherits a raw class

hint: class method


#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)


In [5]:
hint(86)
p, n = 5, 8
M = np.ones((p, n, n))
V = np.ones((p, n, 1))
np.einsum("ijk,ikm->jm", M, V)

hint: np.tensordot


array([[40.],
       [40.],
       [40.],
       [40.],
       [40.],
       [40.],
       [40.],
       [40.]])

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)


In [6]:
hint(87)
matrix = np.ones((16, 16))
added_matrix = np.add.reduceat(
    np.add.reduceat(matrix, np.arange(0, matrix.shape[0], 4), axis=0), np.arange(0, matrix.shape[1], 4), axis=1
)

hint: np.add.reduceat, from numpy.lib.stride_tricks import sliding_window_view (np>=1.20.0)


#### 88. How to implement the Game of Life using numpy arrays? (★★★)


In [7]:
hint(88)

No hints provided...


#### 89. How to get the n largest values of an array (★★★)


In [10]:
hint(89)
vec = np.random.randint(0, 10, 5)
print(vec)
vec[vec.argsort()[-2]]

hint: np.argsort | np.argpartition
[1 8 1 1 4]


4

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)


In [11]:
hint(90)

hint: np.indices


#### 91. How to create a record array from a regular array? (★★★)


In [12]:
hint(91)

hint: np.core.records.fromarrays


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)


In [4]:
Z = np.random.rand(100)
%timeit np.power(Z, 3)
%timeit Z ** 3
%timeit np.einsum("i,i,i->i", Z, Z, Z)

1.54 µs ± 5.06 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
1.54 µs ± 3.64 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
1.11 µs ± 6.16 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)


In [5]:
hint(93)

hint: np.where


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)


In [6]:
hint(94)

No hints provided...


#### 95. Convert a vector of ints into a matrix binary representation (★★★)


In [7]:
hint(95)

hint: np.unpackbits


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)


In [9]:
hint(96)

hint: np.ascontiguousarray | np.unique


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)


In [11]:
hint(97)
A = np.array((1, 2, 3))
B = np.array((2, 3, 4))
print(np.einsum("i,i", A, B))
print(np.einsum("i,j->ij", A, B))
print(np.einsum("i", A))
print(np.einsum("i,i->i", A, B))

hint: np.einsum
20
[[ 2  3  4]
 [ 4  6  8]
 [ 6  9 12]]
[1 2 3]
[ 2  6 12]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?


In [12]:
hint(98)

hint: np.cumsum, np.interp


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)


In [13]:
hint(99)

hint: np.logical_and.reduce, np.mod


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)


In [14]:
hint(100)

hint: np.percentile
